name: Rakuten La
title: Rakuten La | Blog chia sẻ về cuộc sống
description: Đây là một blog chia sẻ về cuộc sống của tôi.
tags:
  - blog
  - lifestyle
  - computer
  - algorithm
  - foreign
email: kenlvq@gmail.com
disqus_username: Phoebus
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
